services:
  grafana:
    user: root
    container_name: 'akdor1154-vega-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/akdor1154-vega-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/akdor1154-vega-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.akdor1154-vega-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: akdor1154-vega-panel
